package com.guru.testing.objectmap;

public enum EditProfilePageObjectMap {

	EDITPROFILE_PAGE_BODY_DIV_ID("ctl00_ctl00_guB_guB_divPanel"),
	EDITPROFILE_PAGE_PROFILE_IMAGE_ID("ctl00_ctl00_guB_guB_aViewProfileLinkImage"),
	EDITPROFILE_PAGE_VIEW_PROFILE_LINK_PLINK("View Profile"),
	EDITPROFILE_PAGE_UPGRADE_MEMBERSHIP_LINK_PLINK("Upgrade Membership"),
	EDITPROFILE_PAGE_EDIT_PROFILE_LINK_ID("lnkHtml_EditProfile"),
	EDITPROFILE_PAGE_SERVICES_LINK_ID("html_lnkServices"),
	EDITPROFILE_PAGE_PORTFOLIO_LINK_ID("html_lnkPortfolio"),
	EDITPROFILE_PAGE_ABOUT_LINK_ID("html_lnkAbout"),
	EDITPROFILE_PAGE_TESTIMONIALS_LINK_ID("html_lnkTest"),
	EDITPROFILE_PAGE_MEMBERSHIP_LINK_ID("html_lnkMembership"),
	EDITPROFILE_PAGE_BIDS_LINK_ID("html_lnkAddBids"),
	EDITPROFILE_PAGE_PROFILE_STATS_LINK_ID("html_lnkProfileStats"),        
	EDITPROFILE_PAGE_COMMON_PANEL_ID("panel1"),
	
	//Edit About info links
	EDITPROFILE_PAGE_EDIT_ABOUT_INFO_COVER_IMG_ID("ctl00_ctl00_guB_guB_ctl00_divBackGroundCover"),
	EDITPROFILE_PAGE_EDIT_ABOUT_INFO_CHANGE_COVER_ID("choosecoverbgImage"),
	EDITPROFILE_PAGE_EDIT_ABOUT_INFO_CHANGE_PROFILE_PIC_ID("chooseProfileImage"),
	EDITPROFILE_PAGE_EDIT_ABOUT_INFO_PROFILE_IMG_XPATH("//img[@class='profileImg']"),
	
	//Edit Services links
	EDITPROFILE_PAGE_EDIT_SERVICES_ADD_BUTTON_ID("buildServBtn"),	
	EDITPROFILE_PAGE_EDIT_SERVICES_ADD_FIRST_SERVICE_PLINK("Add your first service now."),
	EDITPROFILE_PAGE_EDIT_SERVICES_SERVICES_LIST_XPATH("//ul[@id='serviceList']//li"),
	EDITPROFILE_PAGE_EDIT_SERVICES_EDIT_OPTION_DROPDOWN_XPATH("//ul[@class='dropdown-menu pull-right']//a[contains(text(), 'Edit')]"),
	
	
	//Add /EDIT Services Links
	EDITPROFILE_PAGE_SERVICE_TITLE_TEXTBOX_ID("ctl00_ctl00_guB_guB_ctl00_txtServiceName_txtServiceName_DefaultText"),
	EDITPROFILE_PAGE_SERVICE_DESCRIPTION_TEXTBOX_ID("ctl00_ctl00_guB_guB_ctl00_txtDescription_txtDescription_TextBox"),
	EDITPROFILE_PAGE_SERVICE_SKILLS_AND_EXPERTISE_TEXTBOX_ID("token-input-ctl00_ctl00_guB_guB_ctl00_txtSkills_txtSkills_TextBox"),
	EDITPROFILE_PAGE_SERVICE_RATE_PER_HOURS_TEXTBOX_ID("ctl00_ctl00_guB_guB_ctl00_txtRate_txtRate_TextBox"),
	EDITPROFILE_PAGE_SERVICE_MINIMUM_BUDGET_TEXTBOX_ID("ctl00_ctl00_guB_guB_ctl00_txtMinBudget_txtMinBudget_TextBox"),
	EDITPROFILE_PAGE_SERVICE_CATEGORY_DROPDOWN_ID("ctl00_ctl00_guB_guB_ctl00_ddlCategory_ddlCategory_Select"),
	EDITPROFILE_PAGE_SERVICE_PUBLISH_BUTTON_ID("ctl00_ctl00_guB_guB_ctl00_serviceContinue_serviceContinue_Button"),
	EDITPROFILE_PAGE_SERVICE_SAVE_DRAFT_BUTTON_ID("ctl00_ctl00_guB_guB_ctl00_gbDraft_gbDraft_Button"),
	EDITPROFILE_PAGE_SERVICE_CANCEL_BUTTON_ID("cancelservice"),
	EDITPROFILE_PAGE_SERVICE_DESCRIPTION_CHARACTER_TEXT_ID("descCharText"),
	EDITPROFILE_PAGE_SERVICE_ADD_PORTFOLIO_BUTTON_ID("btnAddWork"),
	EDITPROFILE_PAGE_SERVICE_PORTFOLIO_MODAL_ID("addWork"),
	EDITPROFILE_PAGE_SERVICE_PORTFOLIO_MODAL_LIST_XPATH("//ul[@id='workcollectionsList']//li"),	
	EDITPROFILE_PAGE_SERVICE_PORTFOLIO_MODAL_DONE_BUTTON_ID("finishselect"),
	
	
	
	//Edit WC/portfolio
	EDITPROFILE_PAGE_EDIT_PORTFOLIO_PANEL_ID("buildPortfolio"),
	EDITPROFILE_PAGE_EDIT_PORTFOLIO_ADD_BUTTON_ID("addWC"),
	EDITPROFILE_PAGE_EDIT_PORTFOLIO_ADD_FIRST_PORTFOLIO_ID("addWCLink"),
	
	// Add POrtfolio
	
	
	//Add files section
	EDITPROFILE_PAGE_ATTACH_FILES_AND_VIDEOS_DIV_ID("filesList"),
	EDITPROFILE_PAGE_ATTACH_FILES_ADD_ICON_ID("fileCrclIcn"),
	EDITPROFILE_PAGE_LIST_IN_RELATED_WORK_ITEMS_POPUP_XPATH("//ul[@id='workcollectionsList']//li"),
	D_XPATH("//ul[@id='workcollectionsList']//li"),
	EDITPROFILE_PAGE_ATTACH_FILES_FILE_LIST_XPATH("//ul[@id='filesList']//li"),
	EDITPROFILE_PAGE_ATTACH_FILES_DELETE_FILE_ICON_XPATH("//a[@class='module_btn secondary_btn small_btn deletefile']"),
	
	//Add files pop up
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_ID("ctl00_ctl00_guB_guB_ctl00_pnlAttachFilesPopup"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_BROWSE_BUTTON_ID("fuFilesUploader"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_CANCEL_BUTTON_ID("btnCancel"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_CLOSE_ICON_ID("divClose"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_UPLOAD_BUTTON_ID("btnUploadFile"),
	//EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_UPLOAD_MORE_LINK_ID("tdUploadifyButton"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_UPLOAD_MORE_LINK_ID("fuFilesUploader"),
	
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_CANCEL_BUTTON_2_ID("btnCancel2"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_FILE_TABLE_FILE_LIST_ID("queueFiles"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_FILE_TABLE_HEADER_ID("trAttachedFiles"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_FILE_TABLE_FILE_LIST_VALUES_XPATH("//table[@id='queueFiles']//tr"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_PROGRESS_BAR_XPATH("//span[@class='percentage']"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_DONE_BUTTON_ID("btnFinish2"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_DELETE_BIN_ID("fuFilesUploadifyCancel"),
	EDITPROFILE_PAGE_ATTACH_FILES_POP_UP_TOTAL_AND_SIZE_ID("divCount"),
		
	
	
	//common
	EDITPROFILE_PAGE_EDIT_SERVICES_FIRST_SERVICES_OR_PORTFOLIO_XPATH("//div[@class='noservice']"),
	
	
	// ---------------------------------------- PHASE 1 LOCATORS START HERE ----------------------------------------
	
	
	// INVALID INPUT CHECK & ERROR MESSAGE
	EDITPROFILE_PAGE_INVALID_INPUT_XPATH("//input[@class='invalid txtInput']"),
	EDITPROFILE_PAGE_ERROR_MESSAGE_XPATH("//div[@class='errorMsg']"),
	
	// DEALING WITH TESTIMONIALS
	EDITPROFILE_PAGE_EDIT_TESTIMONIALS_ADD_TESTIMONIALS_BUTTON_ID("addfbTest"), 
	EDITPROFILE_PAGE_ADD_TESTIMONIAL_POPUP_ID("buildFeedback"),
	EDITPROFILE_PAGE_ADD_TESTIMONIAL_REVIEWER_NAME_TEXTBOX_ID("ctl00_ctl00_guB_guB_ctl00_txtReviewerName_txtReviewerName_TextBox"),
	EDITPROFILE_PAGE_ADD_TESTIMONIAL_TESTIMONIAL_TEXTBOX_ID("ctl00_ctl00_guB_guB_ctl00_txtTestimonialMessage_txtTestimonialMessage_TextBox"),
	EDITPROFILE_PAGE_ADD_TESTIMONIAL_ADD_BUTTON_ID("ctl00_ctl00_guB_guB_ctl00_btnAddTestimonial_btnAddTestimonial_Button"),
	EDITPROFILE_PAGE_ADD_TESTIMONIAL_CANCEL_BUTTON_ID("btnCancel"),
	EDITPROFILE_PAGE_TESTIMONIAL_LIST_UL_ID("testimonialsList"),
	EDITPROFILE_PAGE_FIRST_TESTIMONIAL_XPATH("(//ul[@id='testimonialsList']//li)[1]"),
	//EDITPROFILE_PAGE_TESTIMONIAL_SAVED_SUCCESS_TOAST_MESSAGE_XPATH("//span[@id='ctl00_ctl00_popMsg'][contains(text(), 'Testimonial Saved Successfully.')]"),
	EDITPROFILE_PAGE_TESTIMONIAL_DROPDOWN_APPEARING_ON_HOVER_XPATH("//a[@class='btnGrayFlat dropdown-toggle']"),
	EDITPROFILE_PAGE_TESTIMONIAL_DROPDOWN_EDIT_OPTION_XPATH("//a[@class='btnEdit']"),
	EDITPROFILE_PAGE_TESTIMONIAL_DROPDOWN_DELETE_OPTION_XPATH("//a[@class='btnDelete']"),
	EDITPROFILE_PAGE_TESTIMONIAL_DROPDOWN_DELETE_CONFIRM_DIALOG_POPUP_ID("confirmDialog"),
	EDITPROFILE_PAGE_DELETE_TESTIMONIAL_POPUP_YES_BUTTON_ID("btnConfirmOK"),
	
	// DEALING WITH PORTFOLIO
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_BUTTON_XPATH("//div[@id='panel1']//button[@id='addWC']"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_FIRST_PORTFOLIO_LINK_ID("addWCLink"),
	EDITPROFILE_PAGE_PORTFOLIO_PORTFOLIO_ADDED_LIST_XPATH("//ul[@id='projectsList']//li"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_XPATH("//div[@class='buildPanel boxSize']"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_PORTFOLIO_NAME_TEXTBOX_XPATH("//input[@id='ctl00_ctl00_guB_guB_ctl01_txtPortfolioName_txtPortfolioName_TextBox'][@class='txtInput']"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_ADD_FILE_XPATH("//li[@class='dividerTb']//a[1]"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_UPLOADED_MEDIA_XPATH("//div[@id='canvas']//li[@class='media image']"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_UPLOADED_MEDIA_THUMBNAIL_XPATH("//div[@id='canvas']//li[@class='media image']//figure[@class='mediaHov']"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_UPLOAD_PROGRESS_ID("ctl00_ctl00_guB_guB_ctl01_pnlUpdateProgress"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_UPLOAD_PROGRESS_XPATH("//div[@class='progressContainer']"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP1_CONTINUE_BUTTON_ID("ctl00_ctl00_guB_guB_ctl01_startPublishCollection_startPublishCollection_Button"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP1_SAVE_BUTTON_ID("btnSave"),
	EDITPROFILE_PAGE_PORTFOLIO_PORTFOLIO_POPUP_STEP1_CANCEL_BUTTON_ID("btnCancelPopup"),
	
	/* Crop related */
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_ADD_COVER_BUTTON_ID("imageChange"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_BOTTOM_TRANSITION_CROP_HANDLE_XPATH("//div[@class='ord-se jcrop-handle']"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_CROP_TRACKER_XPATH("(//div[@class='jcrop-tracker'])[1]"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_CROP_DONE_BUTTON_ID("cropCoverFinish"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_CHANGE_COVER_LINK_ID("changeCover"),
	
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_ADD_TEXT_XPATH("//li[@class='dividerTb']//a[2]"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_ADD_EMBEDDED_MEDIA_XPATH("//li[@class='dividerTb']//a[3]"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_ADD_SKILLS_TEXTBOX_ID("token-input-ctl00_ctl00_guB_guB_ctl01_txtPortfolioSkills_txtPortfolioSkills_TextBox"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_SKILL_AUTOCOMPLETE_BOX_LOOKING_FOR_SKILL_TEXT_XPATH("div[@class='token-input-dropdown']//p[contains(text(), 'Looking for that skill...')]"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_PUBLISH_BUTTON_ID("detailsContinue"),
	EDITPROFILE_PAGE_PORTFOLIO_ADD_PORTFOLIO_POPUP_STEP2_SAVE_BUTTON_ID("SaveSkillsDetailbtn"),
	EDITPROFILE_PAGE_PORTFOLIO_TOAST_MESSAGE_AFTER_SAVING_CHANGES_XPATH("//div[@id='SaveChanges'][@class='popMsg']//p[contains(text(),'Work Collection saved successfully.')]"),
	EDITPROFILE_PAGE_PORTFOLIO_PORTFOLIO_POPUP_STEP2_CANCEL_BUTTON_ID("skipStep"),
	
	EDITPROFILE_PAGE_PORTFOLIO_FIRST_PUBLISHED_PORTFOLIO_XPATH("//ul[@id='projectsList']//div[@class='projCoverMeta']//a[@class='linkpd']"),
	EDITPROFILE_PAGE_PORTFOLIO_PUBLISHED_OR_SAVED_PORTFOLIO_POPUP_PORTFOLIO_NAME_ID("nameofProject"),
	EDITPROFILE_PAGE_PORTFOLIO_PUBLISHED_OR_SAVED_PORTFOLIO_POPUP_XPATH("//div[@class='buildPanel boxSize']"),
	
	/* Dropdown options in a portfolio */
	EDITPROFILE_PAGE_PORTFOLIO_FIRST_PUBLISHED_PORTFOLIO_DROPDOWN_BUTTON_XPATH("//ul[@id='projectsList']//button[@class='module_btn secondary_btn btn-small dropdown-toggle']"),
	EDITPROFILE_PAGE_PORTFOLIO_FIRST_DRAFT_PORTFOLIO_DROPDOWN_BUTTON_XPATH("//ul[@id='draftsList']//button[@class='module_btn secondary_btn btn-small dropdown-toggle']"),
	EDITPROFILE_PAGE_PORTFOLIO_FIRST_PUBLISHED_PORTFOLIO_DROPDOWN_COPY_OPTION_XPATH("//a[@class='copydrafts']"),
	EDITPROFILE_PAGE_PORTFOLIO_FIRST_PUBLISHED_PORTFOLIO_DROPDOWN_UNPUBLISH_OPTION_XPATH("//a[@class='unpublish']"),
	EDITPROFILE_PAGE_PORTFOLIO_FIRST_PUBLISHED_PORTFOLIO_DROPDOWN_DELETE_OPTION_XPATH("//a[@class='deletepublished']"),
	EDITPROFILE_PAGE_PORTFOLIO_DRAFT_SECTION_FIRST_DRAFT_DROPDOWN_PUBLISH_OPTION_XPATH("//a[@class='publish']"),
	EDITPROFILE_PAGE_PORTFOLIO_DRAFT_SECTION_FIRST_DRAFT_DROPDOWN_DELETE_OPTION_XPATH("//a[@class='deleteunpublished']"),
	EDITPROFILE_PAGE_PORTFOLIO_DELETE_CONFIRM_YES_ID("btnConfirmOK"),
	EDITPROFILE_PAGE_PORTFOLIO_DELETE_CONFIRM_NO_ID("btnConfirmCancel"),
	EDITPROFILE_PAGE_PORTFOLIO_DRAFT_SECTION_FIRST_DRAFT_DROPDOWN_COPY_OPTION_XPATH("//a[@class='copydrafts1']"),
	
	/* Draft section */
	EDITPROFILE_PAGE_PORTFOLIO_DRAFT_SECTION_UL_ID("draftsList"),
	EDITPROFILE_PAGE_PORTFOLIO_DRAFT_SECTION_HEADER_XPATH("//span[contains(text(),'Drafts')]"),
	EDITPROFILE_PAGE_PORTFOLIO_DRAFT_SECTION_FIRST_DRAFT_XPATH("//ul[@id='draftsList']//li[@class='item draggable1']//a[@class='linkpd']"),
	
	EDITPROFILE_PAGE_PORTFOLIO_TOAST_MESSAGE_AFTER_UNPUBLISHING_PORTFOLIO_XPATH("//div[@id='SocialLink'][@class='popMsg']//p[contains(text(),'has been moved to drafts.')]"),
	EDITPROFILE_PAGE_PORTFOLIO_TOAST_MESSAGE_AFTER_PUBLISHING_PORTFOLIO_XPATH("//div[@id='SocialLink'][@class='popMsg']//p[contains(text(),'has been published.')]"),
	EDITPROFILE_PAGE_PORTFOLIO_TOAST_MESSAGE_AFTER_COPYING_PORTFOLIO_XPATH("//div[@id='SocialLink'][@class='popMsg']//p[contains(text(),'has been copied to drafts.')]"),
	
	EDITPROFILE_PAGE_VIEW_PROFILE_LINK_XPATH("//a[contains(text(), 'View Profile')]"),

	
	;
	         
	private final String value;
	EditProfilePageObjectMap(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return this.getValue();
    }


}
