package com.guru.testing.objectmap;

public enum PaymentsTransferPageObjectMap {
	
	PAYMENTS_PAGE_TRANSFER_METHODS_REMOVE_LINK_XPATH("//a[contains(text(), 'Remove')]"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CONFIRM_REMOVE_XPATH("//input[@value='Remove Transfer Method']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_METHODS_LIST_XPATH("(//ul[@class='paymethods'])[3]"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_TRANSFER_METHOD_DROPDOWN_BTN_XPATH("//button[contains(text(), 'Add Transfer Method')]"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_TRANSFER_METHOD_DROPDOWN_OPTIONS_XPATH("//ul[@class='module_list dropdown-menu']//li"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_BANK_ACCOUNT_POPUP_ACCOUNT_TYPE_DROPDOWN_ID("accountType"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_BANK_ACCOUNT_POPUP_ACCOUNT_HOLDER_NAME_TEXTBOX_XPATH("//input[@ng-model='newBank.fullName']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_BANK_ACCOUNT_POPUP_ROUTING_NUMBER_TEXTBOX_XPATH("//input[@ng-model='newrouting']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_BANK_ACCOUNT_POPUP_ROUTING_NUMBER_SUGGESTION_XPATH("//li[@role='option']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_BANK_ACCOUNT_POPUP_ACCOUNT_NUMBER_TEXTBOX_XPATH("//input[@ng-model='newBank.accountNumber']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_BANK_ACCOUNT_POPUP_CONFIRM_ACCOUNT_NUMBER_TEXTBOX_XPATH("//input[@ng-model='newBank.confirmaccountNumber']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_ADD_BANK_ACCOUNT_POPUP_ADD_BANK_ACCOUNT_BUTTON_XPATH("//input[@value='Add Bank Account']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_BANK_ACCOUNT_ADDED_TOAST_MESSAGE_XPATH("//p[contains(@class, 'module_toast')][contains(text(), 'Bank account added')]"),
	PAYMENTS_PAGE_TRANSFER_METHODS_PAY_METHODS_LIST_CONTAINTER_XPATH("//ul[@class='paymethods']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_PAY_METHODS_INFO_XPATH("//ul[@class='paymethods']//li//div[@class='module_avatar']"),
	
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_PREFERRED_CURRENCY_SELECT_DROPDOWN_XPATH("//select[@ng-model='newWT.currency']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_BILLING_ADDRESS_DIV_CONTAINER_XPATH("//div[contains(@class, 'billingAddress')]"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_ACCOUNT_TEXTBOX_XPATH("//input[@ng-model='newWT.iban']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_SWIFT_1_TEXTBOX_XPATH("//input[@ng-model='newWT.swift']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_SWIFT_1_LOOKUP_BUTTON_XPATH("(//div[@class='input-group']//span[contains(text(), 'Lookup')])[1]"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_SWIFT_2_TEXTBOX_XPATH("//input[@ng-model='newWT.Intermediary_swift']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_SWIFT_2_LOOKUP_BUTTON_XPATH("(//div[@class='input-group']//span[contains(text(), 'Lookup')])[2]"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_ADDITIONAL_NOTES_TEXTBOX_XPATH("//textarea[@ng-model='newWT.notes']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_I_AGREE_CHECKBOX_ID("wt_agree"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_I_AUTHORIZE_CHECKBOX_ID("wt_agree2"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_ADD_WIRE_TRANSFER_ACCOUNT_BUTTON_XPATH("//input[@value='Add Wire Transfer Account']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_WIRE_TRANSFER_BANK_FOUND_AS_PER_SWIFT_XPATH("//div[@class='inputChunk ng-scope']"),
	
	// ---- CREDIT CARD POPUP ----
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_CONTAINER_XPATH("//div[@aria-labelledby='addCreditCardLabel']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_CARD_NUMBER_TEXTBOX_XPATH("//input[@ng-model='newCC.ccnumber']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_SELECT_MONTH_DROPDOWN_XPATH("//select[@ng-model='newCC.month']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_SELECT_YEAR_DROPDOWN_XPATH("//select[@ng-model='newCC.year']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_SECURITY_CODE_TEXTBOX_XPATH("//input[@ng-model='newCC.cvv']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_NAME_ON_CARD_TEXTBOX_XPATH("//input[@ng-model='newCC.address.fullName']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_SELECT_COUNTRY_DROPDOWN_XPATH("//select[@ng-model='newCC.address.country']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_STREET_ADDRESS_TEXTBOX_XPATH("//input[@ng-model='newCC.address.street']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_CITY_TEXTBOX_XPATH("//input[@ng-model='newCC.address.city']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_SELECT_STATE_DROPDOWN_XPATH("//select[@ng-model='newCC.address.state']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_ZIP_TEXTBOX_XPATH("//input[@ng-model='newCC.address.zip']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_BILLING_AND_STREET_ADDRESS_BOX_XPATH("//div[@class='module_box editBilling']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_ADD_CREDIT_CARD_BUTTON_XPATH("//input[@value='Add Credit Card']"),
	PAYMENTS_PAGE_TRANSFER_METHODS_CREDIT_CARD_POPUP_CANCEL_BUTTON_ID("cancelPopup"),
	;
	
	private final String value;
	PaymentsTransferPageObjectMap(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return this.getValue();
    }
	
}
